### ISSUE TITLE
Rules are broken against bazel master

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/rules_apple#127]
One cannot use ios_application after with a bazel built after https://github.com/bazelbuild/bazel/commit/86fdf0b2495888fc2c3e8c84e0b2f02f566187f9

This error is emitted

```
	File "/private/var/tmp/_bazel_lewis/4a25cfc2b9b758043413ac58525ef6b4/external/build_bazel_rules_apple/apple/bundling/ios_rules.bzl", line 137, in _ios_application_impl
		test_support.new_xctest_app_provider(ctx)
	File "/private/var/tmp/_bazel_lewis/4a25cfc2b9b758043413ac58525ef6b4/external/build_bazel_rules_apple/apple/bundling/test_support.bzl", line 83, in test_support.new_xctest_app_provider
		apple_common.new_xctest_app_provider(bundle_loader = binary_file, ipa =..., ...))
type 'apple_common' has no method new_xctest_app_provider(File bundle_loader, File ipa, ObjcProvider objc_provider)
```

**Comment by sergiocampama** [comment]
We have just merged a (quite big) PR updating the repo. Would you mind testing this head release against head bazel now?

**Comment by allevato** [comment]
For reference, the PR was #128. Unfortunately a lot of our history had to get squashed, so there are a number of changes there.

We're also in the process of trying to set up a good CI solution to keep this repo and Bazel releases better tested.

**Comment by thaidn** [comment]
I got this error, using Bazel 0.9.0 and rules_apple HEAD:

ERROR: /Volumes/BuildData/tmpfs/src/git/cloudcryptosdk/objc/BUILD:141:1: in _ios_test_bundle rule //objc:TinkTests_test_bundle: 
Traceback (most recent call last):
	File "/Volumes/BuildData/tmpfs/src/git/cloudcryptosdk/objc/BUILD", line 141
		_ios_test_bundle(name = 'TinkTests_test_bundle')
	File "/private/var/tmp/_bazel_kbuilder/c0f2e5fa15f18957c64555e671eb8a9b/external/build_bazel_rules_apple/apple/testing/ios_rules.bzl", line 35, in _ios_test_bundle_impl
		apple_test_bundle_support.apple_test_bundle_impl(ctx, "IosTestArchive", "IosTest", [Ios...()])
	File "/private/var/tmp/_bazel_kbuilder/c0f2e5fa15f18957c64555e671eb8a9b/external/build_bazel_rules_apple/apple/testing/apple_test_bundle_support.bzl", line 72, in apple_test_bundle_support.apple_test_bundle_impl
		binary_support.get_binary_provider(ctx.attr.deps, apple_common.AppleLoadableBundleBinary).objc
'AppleLoadableBundleBinary' object has no attribute 'objc'
Available attributes: binary

The test rule can be found at https://github.com/google/tink/blob/master/objc/BUILD#L141.

Please advise.

**Comment by StevenEWright** [comment]
@thaidn it looks like that field was only added to Bazel head 13 days ago here: https://github.com/bazelbuild/bazel/commit/8134b9fc140c810d00a91ca9a0313a1e4322ee00

**Comment by thaidn** [comment]
Ah so I need to use Bazel at HEAD?

Which version of rules_apple work with Bazel 0.9.0?

**Comment by StevenEWright** [comment]
I can't give any official advice. I don't know what the owners' plans are here. Until we hear...

You could update Bazel, as you say (fortunately).

Or you could pin to a tag (best) or commit (better).

**0.2.0 Tag**

```
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.2.0",
)
```

**Commit before bazelbuild/bazel@86fdf0b**

```
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    commit = "a2b620070d373e4f265194b69f65e9e5c17fbcb8",
)
```

**Comment by thaidn** [comment]
Using a commit before bazelbuild/bazel@86fdf0b works. Thanks @StevenEWright.

**Comment by sergiocampama** [comment]
Closing as obsolete
