### ISSUE TITLE
ios_application broken since 3a8d7fb0d47a946df7bc89f325a36f377b706396

### ISSUE THREAD

**Issue by ajanuar** [bazelbuild/rules_apple#1088]
ios_application broken since 3a8d7fb0d47a946df7bc89f325a36f377b706396.

```
ERROR: /Users/albertjanuar/Documents/traveloka/district-traveloka/packages/apps/ios/Traveloka/Modules/TVLUITestKit/BUILD:127:16: in ios_application rule //Modules/TVLUITestKit:SandboxApp:
Traceback (most recent call last):
	File "/Users/albertjanuar/Documents/traveloka/district-traveloka/packages/apps/ios/Traveloka/bazel-ios/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 115, column 58, in _ios_application_impl
		link_result = linking_support.register_linking_action(
	File "/Users/albertjanuar/Documents/traveloka/district-traveloka/packages/apps/ios/Traveloka/bazel-ios/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 102, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
```

**Comment by thii** [comment]
Are you using Bazel 3.x? You will need Bazel 4.0 because that API is only available since Bazel 4.0.

**Comment by ajanuar** [comment]
Ah ok, i am still at 3.7.2. Thanks!
