### ISSUE TITLE
SDK not supported by the compiler

### ISSUE THREAD

**Issue by erneestoc** [bazelbuild/rules_apple#2231]
Using 3.0.0-rc1

When attempting to import `facebook-ios-sdk` static framework, using `apple_static_xcframework_import`, it's giving the following error:
```
Sources/HelloWorld.swift:1:8: error: failed to build module 'FBSDKLoginKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.
import FBSDKLoginKit
```

However, this works on Xcode 14.3.1 using Swift 5.8.1.

[Sample Project](https://github.com/erneestoc/bazel-fb-sdk-bug)
Steps to reproduce:
run `bazel build //:FbExample` on the sample project

**Comment by keith** [comment]
The part of the error you included is a red herring. The actual error is because the required dependencies aren't included in the build:

```
error: no such module 'FBSDKCoreKit_Basics'
import FBSDKCoreKit_Basics
```

Here's a working BUILD file:

```bzl
load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "apple_static_xcframework_import",
)

apple_static_xcframework_import(
    name = "FBSDKLoginKit",
    visibility = ["//visibility:public"],
    xcframework_imports = glob(
        ["FBSDKLoginKit.xcframework/**"],
    ),
    deps = ["FBSDKCoreKit"],
)

apple_static_xcframework_import(
    name = "FBSDKCoreKit",
    visibility = ["//visibility:public"],
    xcframework_imports = glob(
        ["FBSDKCoreKit.xcframework/**"],
    ),
    deps = ["FBAEMKit"],
)

apple_static_xcframework_import(
    name = "FBAEMKit",
    visibility = ["//visibility:public"],
    xcframework_imports = glob(
        ["FBAEMKit.xcframework/**"],
    ),
    deps = ["FBSDKCoreKit_Basics"],
)

apple_static_xcframework_import(
    name = "FBSDKCoreKit_Basics",
    visibility = ["//visibility:public"],
    xcframework_imports = glob(
        ["FBSDKCoreKit_Basics.xcframework/**"],
    ),
)
```

I guess the logic on the swift compiler side must be to show the version mismatch as an error _if_ it is failing.

**Comment by erneestoc** [comment]
Forgot to update this issue, you were right, thanks!
